#!/bin/sh
export USER=root
export HOME=/root

case `uname -m` in
	aarch64)
		archurl="aarch64" ;;
	arm*)
		archurl="arm" ;;
	amd64)
		archurl="x86_64" ;;
	x86_64)
		archurl="x86_64" ;;	
	i*86)
		archurl="i386" ;;
	x86)
		archurl="i386" ;;
	*)
		echo "unknown architecture"; exit 1 ;;
	esac

LD_PRELOAD=/lib/${archurl}-linux-gnu/libgcc_s.so.1 vncserver -name remote-desktop -localhost no :1
